project:
  type: website

website:
  title: "Richard McDonald"
  description: "Richard McDonald is an earth scientist with a broad range of interests in computational hydrology and geomorphology."
  image: logo.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



